# Generated by Django 3.2.5 on 2021-07-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('data_de_coleta', models.DateTimeField()),
                ('tipo_de_material', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('virus', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('data_de_solicitacao', models.DateTimeField()),
                ('data_de_execucao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('data_de_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_amostra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.amostra')),
                ('codigo_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.exame')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Outros_Dados_Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.CharField(max_length=255)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Outros_Dados_Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.CharField(max_length=255)),
                ('codigo_amostra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.amostra')),
            ],
        ),
        migrations.AddField(
            model_name='amostra',
            name='codigos_exames',
            field=models.ManyToManyField(through='main.Possui', to='main.Exame'),
        ),
    ]
