# Generated by Django 3.2.5 on 2021-07-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='id',
        ),
        migrations.AlterField(
            model_name='amostra',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exame',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
