# Generated by Django 3.2.5 on 2021-07-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210716_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='tipo_de_material',
            field=models.CharField(max_length=255),
        ),
    ]
