# Generated by Django 3.2.5 on 2021-07-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210716_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='outros_dados_amostra',
            name='codigo_amostra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.amostra'),
        ),
        migrations.AlterField(
            model_name='outros_dados_paciente',
            name='cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
