# Generated by Django 3.2.5 on 2021-07-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210716_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possui',
            name='codigo_amostra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.amostra'),
        ),
    ]
