# Generated by Django 3.2.5 on 2021-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_amostra_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
