# Generated by Django 3.2.5 on 2021-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210722_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='cpf',
        ),
        migrations.AddField(
            model_name='amostra',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
