# Generated by Django 3.2.5 on 2021-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210722_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='cpfs',
            field=models.ManyToManyField(through='main.Possui', to='main.Paciente'),
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='cpf',
        ),
        migrations.AddField(
            model_name='amostra',
            name='cpf',
            field=models.CharField(default=5, max_length=11),
            preserve_default=False,
        ),
    ]
