# Generated by Django 3.2.5 on 2021-07-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210722_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='cpfs',
        ),
    ]
