# Generated by Django 3.2.5 on 2021-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_amostra_cpfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='cpfs',
            field=models.ManyToManyField(through='main.Possui', to='main.Paciente'),
        ),
    ]
