# Generated by Django 3.2.5 on 2021-07-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_amostra_cpfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='codigos_exames',
        ),
        migrations.RemoveField(
            model_name='amostra',
            name='cpfs',
        ),
    ]
