# Generated by Django 3.2.5 on 2021-07-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_possui_codigo_amostra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possui',
            name='codigo_amostra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.amostra'),
        ),
        migrations.AddConstraint(
            model_name='possui',
            constraint=models.UniqueConstraint(fields=('cpf', 'codigo_exame', 'codigo_amostra'), name='unique_exame_amostra'),
        ),
    ]
