# Generated by Django 3.2.5 on 2021-07-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': (False,)},
        ),
        migrations.AlterModelOptions(
            name='usuario_possui_perfil',
            options={'managed': (False,)},
        ),
    ]
