# Generated by Django 3.2.5 on 2021-07-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ep3', '0002_auto_20210707_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario_possui_perfil',
            options={},
        ),
    ]
